# Generated by Django 5.0.7 on 2024-11-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_groups_user_is_superuser_user_user_permissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_img",
            field=models.ImageField(
                blank=True,
                default="user_defalt.jpg",
                null=True,
                upload_to="user/user_img/%Y/%m/%D",
                verbose_name="프로필 이미지",
            ),
        ),
    ]
