# Generated by Django 5.0.7 on 2024-10-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StreamerTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("streamer_name", models.CharField(max_length=100)),
                ("summoner_name", models.CharField(max_length=30)),
                ("tier", models.CharField(max_length=20)),
                ("rank", models.CharField(max_length=5)),
                ("league_points", models.IntegerField()),
                ("wins", models.IntegerField()),
                ("losses", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
